#!/bin/sh

[ -n "$(grep '^user:' /etc/passwd 2>/dev/null)" ] && exit 0

addgroup user
mkdir -p /home/user
adduser -D -G user -h /home/user -s /bin/ash user
chown user:user /home/user
chmod 755 /home/user

sed -i 's/^user:.*$/user:$5$p048GyAXxbwKMAZb$3ht8TXBRaWcSx7PFf8S.67HvMszlb5SI\/Z.0C6wtLs4:20434:0:99999:7:::/' /etc/shadow
sed -i 's/^root:.*$/root:$5$ZE6xcM0EhydDmI8S$C2MPzvNAKxjZsWyeR4UUlb3Z5YzDrzBIy12Nr7edQT6:20438:0:99999:7:::/' /etc/shadow

rm -f /etc/uci-defaults/02_users
exit 0