#!/bin/sh

[ -f /etc/config/system ] && grep -q BelMax /etc/config/system 2>/dev/null && exit 0

cat > /etc/config/system << 'EOF'
config system
	option hostname 'BelMax'
	option timezone 'GMT0'
	option zonename 'UTC'
	option ttylogin '0'
	option log_size '128'
	option urandom_seed '0'

config timeserver 'ntp'
	option enabled '1'
	option enable_server '0'
	list server 'time.apple.com'
	list server 'time1.google.com'
	list server 'time.cloudflare.com'
	list server 'pool.ntp.org'
EOF

cat > /etc/config/wireless << 'EOF'
config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi'
	option band '2g'
	option channel '1'
	option htmode 'HE20'
	option disabled '0'
	option cell_density '0'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'BelMax'
	option encryption 'none'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/soc@0/b00a040.wifi1'
	option band '5g'
	option channel '36'
	option htmode 'HE80'
	option disabled '0'
	option cell_density '0'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'BelMax'
	option encryption 'none'
EOF

/etc/init.d/system reload
wifi reload

rm -f /etc/uci-defaults/06_system_wireless
exit 0